--mysql
SELECT T1.ID, T2.AGE, T1.COINS_NEEDED, T1.POWER
FROM WANDS T1
 INNER JOIN WANDS_PROPERTY T2 ON T1.CODE = T2.CODE
WHERE T2.IS_EVIL = 0
AND T1.COINS_NEEDED IN (SELECT MIN(COINS_NEEDED)
                       FROM WANDS A
                       INNER JOIN WANDS_PROPERTY B ON A.CODE=B.CODE
                       WHERE B.IS_EVIL = 0
                       AND T1.POWER = A.POWER
                       AND T2.AGE = B.AGE)
ORDER BY T1.POWER DESC, T2.AGE DESC


