--mysql
SELECT HACKERS.HACKER_ID, HACKERS.NAME, COUNT(*) AS CHALLENGES_CREATED
FROM HACKERS
 INNER JOIN CHALLENGES ON HACKERS.HACKER_ID = CHALLENGES.HACKER_ID
GROUP BY HACKERS.HACKER_ID, HACKERS.NAME
HAVING CHALLENGES_CREATED = (
SELECT MAX(T1.C)
FROM (SELECT COUNT(*) AS C
FROM CHALLENGES
GROUP BY HACKER_ID) T1
) OR CHALLENGES_CREATED IN (
SELECT T2.C
FROM (SELECT COUNT(*) AS C
FROM CHALLENGES
GROUP BY HACKER_ID) T2
GROUP BY T2.C
HAVING COUNT(T2.C) = 1
)
ORDER BY CHALLENGES_CREATED DESC, HACKERS.HACKER_ID