--mysql
SELECT H.HACKER_ID, H.NAME, T2.TOTAL_SCORE
FROM (SELECT T1.HACKER_ID, SUM(MAX_SCORE) AS TOTAL_SCORE
     FROM (SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS MAX_SCORE
          FROM SUBMISSIONS
          GROUP BY HACKER_ID, CHALLENGE_ID) T1
      GROUP BY T1.HACKER_ID
      HAVING TOTAL_SCORE != 0) T2
 INNER JOIN HACKERS H ON T2.HACKER_ID = H.HACKER_ID
ORDER BY T2.TOTAL_SCORE DESC, H.HACKER_ID